Catch missing socket.
Can be caused by the race condition of a slow spectator joining and the
message arriving after the player has quit. I think...

2015-07-01 02:01:44,354 INFO: #9     Session user: dontdoit
2015-07-01 02:01:50,181 WARN: #9     Error while handling JSON message!
Traceback (most recent call last):
  File "ws_handler.py", line 714, in on_message
    handler(**obj)
  File "ws_handler.py", line 350, in start_crawl
    self.process.add_watcher(self)
  File "process_handler.py", line 587, in add_watcher
    self.conn.send_message('{"msg":"spectator_joined"}')
  File "connection.py", line 90, in send_message
    self.socket.sendto(data, self.crawl_socketpath)
error: [Errno 2] No such file or directory